### PR TITLE
Release-Beta

### PR DESCRIPTION
**Pull request by hughesd22**
Requesting final approval from @reactivepixel

- [Staging Server](https://study-up-pup.herokuapp.com/)
- [Production Server](https://study-up-pup-prod.herokuapp.com/)

Staging Server is currently running the Alpha Release.
Production Server is currently running the Pivot Release.

After the Beta Release is approved, will be manually deploying the Alpha Release onto the Production Server. I will then merge the Beta Release, which will be automatically deployed to the Staging Server by Heroku.

(Post Beta-Release: Production Server will run Alpha Release, Staging Server will run Beta Release).

### CODE REVIEW

**Comment by hughesd22** [comment]
@reactivepixel I currently don't have data in the database to display lessons from in the Train section. I'll fix that.

The design is not polished yet, and I was about to create issues regarding that. I'll take care of that now.

I'll tag you once I make the changes. 👍

**Comment by hughesd22** [comment]
Lesson issue is addressed in issue https://github.com/hughesd22/study-up-pup/issues/97

**Comment by hughesd22** [comment]
Breathing Room Around Text issue is resolved in issue https://github.com/hughesd22/study-up-pup/issues/96

**Comment by hughesd22** [comment]
@reactivepixel I made the requested changes.

I am requesting final approval

**Comment by hughesd22** [comment]
Requesting final approval from @reactivepixel

**Comment by reactivepixel** [comment]
@hughesd22 Upon creating a duplicate user account there is no prompt to the user that there was an error (should be) Please ensure this is resolved for the final public release.

**Pull request merged**
